config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'

  devise_for :admin_users, ActiveAdmin::Devise.config
  devise_for :customers, controllers: {
                           sessions: 'customers/sessions',
                           registrations: 'customers/registrations',
                           passwords: 'customers/passwords'
                       }

  ActiveAdmin.routes(self)
  get '/admin/products/:id/clone' => 'admin/products#new', :as => :admin_clone_product
  get '/admin/templates/:id/export' => 'admin/templates#export', :as => :admin_export_template
  get '/admin/templates/import' => 'admin/templates#import', :as => :admin_import_template
  get '/admin/shopping_orders/:id/invoice' => 'admin/shopping_orders#invoice', :as => :admin_invoice_shopping_order

  resource :categories, only: [] do
    get '/' => 'categories#index'
    get '/:slug' => 'categories#show', as: :show_slug
    get '/:id/show' => 'categories#show', as: :show_id
    get '/:category_slug/products/:slug' => 'products#show', as: :show_product_slug
    match '/:slug/tag/*slug_tags' => 'categories#tags', as: :tags, via: [:get]
  end

  match '/tag/*slug_tags' => 'categories#tags', as: :tags, via: [:get]

  resource :products, only: [] do
    get '/:slug' => 'products#show', as: :show_slug
    get '/:id/show' => 'products#show', as: :show_id
    get '/:id/add_to_shopping_cart' => 'products#add_to_shopping_cart', as: :add_to_shopping_cart
    get '/:id/delete_from_shopping_cart' => 'products#delete_from_shopping_cart', as: :delete_from_shopping_cart
  end

  resource :searches, only: [] do
    post '/' => 'searches#index'
  end

  resource :customers, only: [] do
    get '/show' => 'customers#show'
    get '/orders' => 'customers#orders'
    get '/orders/:id/invoice' => 'customers#invoice', as: :orders_invoice

    resources :addresses
    resource :shopping_carts, only: [] do
      get '/' => 'shopping_carts#show'
      post '/:product_id/update' => 'shopping_carts#update', as: :update
    end

    resource :shopping_orders, only: [] do
      get '/shipping_method' => 'shopping_orders#shipping_method'
      get '/:type/addresses' => 'shopping_orders#addresses', as: :addresses
      get '/:type/:id/save_address' => 'shopping_orders#save_address', as: :save_address

      post '/save_carrier' => 'shopping_orders#save_carrier'
      get '/checkout' => 'shopping_orders#checkout'
      get '/finalize' => 'shopping_orders#finalize'
    end
  end

  get '/locale/:locale' => 'application#change_locale', :as => 'change_locale'

  scope '/api' do
    scope '/v1' do
      scope '/data_forms' do
        post '/' => 'api/data_forms#create'
      end
    end
  end

  root 'home#index'

end

app/models/shopping_cart.rb
# == Schema Information
#
# Table name: shopping_carts
#
#  billing_address_id   :integer
#  carrier_id           :integer
#  carrier_retail_price :decimal(10, 2)   default(0.0), not null
#  created_at           :datetime         not null
#  customer_id          :integer
#  id                   :integer          not null, primary key
#  shipping_address_id  :integer
#  updated_at           :datetime         not null
#
# Indexes
#
#  index_shopping_carts_on_customer_id  (customer_id)
#
# Foreign Keys
#
#  fk_rails_7725ef05cb  (billing_address_id => customer_addresses.id)
#  fk_rails_95c2cdac1a  (shipping_address_id => customer_addresses.id)
#  fk_rails_a4cc6e935e  (customer_id => customers.id)
#

class ShoppingCart < ActiveRecord::Base
  include ArrayLiquid

  belongs_to :carrier
  belongs_to :customer
  has_many :shopping_carts_products, autosave: true

  belongs_to :shipping_address, touch: true, class_name: 'CustomerAddress', foreign_key: 'shipping_address_id'
  belongs_to :billing_address, touch: true, class_name: 'CustomerAddress', foreign_key: 'billing_address_id'

  before_save :calculate_shipping_cost

  def initialize(attributes = {}, options = {})
    super

    self.shipping_address = customer.shipping_address unless customer.nil?
    self.billing_address = customer.billing_address unless customer.nil?
  end

  def total_products
    shopping_carts_products.inject(0) { |a, e| a + e.quantity }
  end

  def total_weight
    shopping_carts_products.inject(0) { |a, e| a + (e.product.weight * e.quantity) }
  end

  def total_retail_price
    array_prices = shopping_carts_products.map { |e| e.product.retail_price * e.quantity }
    products_prices = array_prices.reduce(:+)
    products_prices ||= 0

    products_prices + carrier_retail_price
  end

  def remove_product(product)
    shopping_carts_products.where(product_id: product.id).destroy_all
  end

  def update_product(product_id, quantity)
    shopping_carts_products.each do |scp|
      if scp.product_id == product_id
        scp.quantity = quantity
        break
      end
    end
  end

  def add_product(product)
    scp = shopping_carts_product(product)

    if scp.nil?
      scp = ShoppingCartsProduct.new
      scp.product = product
      shopping_carts_products << scp
    else
      scp.quantity += 1
    end

    scp.retail_price = product.retail_price
    scp.save unless id.nil?
    scp
  end

  def self.retrieve(customer, session_variable)
    sc = customer.shopping_cart unless customer.nil?
    sc ||= ShoppingCart.new(customer: customer)

    ShoppingCart.retrieve_products(sc, session_variable)
    sc.save unless customer.nil?
    sc
  end

  def to_liquid
    {
        'shopping_carts_products' => array_to_liquid(shopping_carts_products),
        'total_products' => total_products,
        'total_weight' => total_weight,
        'total_retail_price' => total_retail_price
    }
  end

  private

  def calculate_shipping_cost
    self.carrier_retail_price = 0

    if !shipping_address.nil? && !carrier.nil?
      country_code = shipping_address.country
      self.carrier_retail_price = carrier.calculate_shipping_cost_to(country_code, total_weight)
    end
  end

  def shopping_carts_product(product)
    shopping_carts_products.each do |scp|
      return scp if scp.product_id == product.id
    end

    nil
  end

  def self.retrieve_products(sc, session_variable)
    # Load shopping cart from session variable.
    unless session_variable.blank?
      hash = ActiveSupport::JSON.decode(session_variable)

      sc.shopping_carts_products = []
      hash['shopping_carts_products'].each do |scp|
        sc.shopping_carts_products << ShoppingCartsProduct.new(scp)
      end
    end
  end
end

app/controllers/shopping_carts_controller.rb
class ShoppingCartsController < Frontend::CommonController
  layout 'shopping'

  def get_template_variables(template)
    super
  end

  def show
    add_breadcrumb(Breadcrumb.new(url: customers_shopping_carts_path, name: 'Cart'))
  end

  def update
    params_scp = params_shopping_cart

    sc = ShoppingCart.retrieve(current_customer, session[:shopping_cart])
    sc.update_product(params_scp[:product_id].to_i, params_scp[:quantity].to_i)

    if customer_signed_in?
      sc.save
    else
      session[:shopping_cart] = sc.to_json(include: :shopping_carts_products)
    end

    redirect_to :customers_shopping_carts
  end

  protected

  def set_breadcrumbs
    add_breadcrumb(Breadcrumb.new(url: show_customers_path, name: 'Customers'))
  end

  def params_shopping_cart
    params.permit(:product_id, :quantity)
  end
end

app/helpers/shopping_carts_helper.rb
module ShoppingCartsHelper
end

app/views/shopping_carts/show.html.haml
%h1 Cart

- if !@variables['shopping_cart'].nil? && @variables['shopping_cart'].shopping_carts_products.any?
  %ul.list-unstyled
    %li
      %div.row
        %div{class: 'col-md-6 col-xs-6'}
        %div{class: 'col-md-3 col-xs-3'}
          Price
        %div{class: 'col-md-3 col-xs-3'}
          Quantity

    - @variables['shopping_cart'].shopping_carts_products.each do |scp|
      - product = scp.product
      %li.sc-list-item-border

        %div.row
          %div{class: 'col-md-6 col-xs-6'}
            %div{:class => 'item-image col-md-3'}
              = image_tag product.retrieve_main_image(:thumbnail)
            %div{:class => 'col-md-9 col-xs-12'}
              = link_to product.name, show_slug_products_path(product.slug)
              %br
              = link_to 'remove', delete_from_shopping_cart_products_path(product)
          %div{class: 'col-md-3 col-xs-3'}
            %div.a-color-price
              = "#{product.retail_price} €"
          %div{class: 'col-md-3 col-xs-3'}
            %div.col-md-12
              %div.form-group
                %div{id:"form-quantity-#{scp.id}", class: 'hidden'}
                  = form_tag update_customers_shopping_carts_path(product.id), method: 'post' do
                    %div.col-md-8
                      %input{id: "input-quantity-#{scp.id}", type: 'number', name: 'quantity', min: '1', value: scp.quantity, class: 'form-control'}
                    %div.col-md-4
                      %input{type: 'submit', value: 'Submit', class: 'btn btn-warning'}

                %div{id: "select-quantity-#{scp.id}", :class => 'btn-group', :role => 'group'}
                  %button{:type => 'button', :class => 'btn btn-default dropdown-toggle', 'data-toggle' => 'dropdown', 'aria-expanded' => 'false'}
                    = scp.quantity
                    %span.caret

                  %ul{:class => 'dropdown-menu', :role => 'menu'}
                    - (1..9).each do |i|
                      %li
                        %a{href: "javascript:modify_quantity_form(#{scp.id}, #{i});"}
                          = i
                    %li{:role => 'presentation', :class => 'divider'}
                    %li
                      %a{onclick: "javascript:show_quantity_form(#{scp.id});"}
                        10+

    %li.sc-list-item-border
      %div.row
        %div{class: 'col-md-6'}
        %div{class: 'col-md-6 col-xs-12'}
          %div.pull-right
            %span
              = "Subtotal (#{@variables['shopping_cart'].total_products} products): "
            %span.a-color-price
              = "#{@variables['shopping_cart'].total_retail_price} €"
- else
  %div.row
    %div.col-md-12
      %div{:class => 'alert alert-warning', :role => 'alert'}
        %span{:class => 'fa fa-exclamation-triangle', 'aria-hidden' => 'true'}
        %i Your cart is empty.

%div{class: 'row voffset3'}
  %div{class: 'col-md-2'}
    = link_to 'Continue shopping', @variables['commerce']['root_href'], class: 'btn btn-block btn-default'
  %div{class: 'col-md-offset-8 col-md-2'}
    = link_to 'Shipping', shipping_method_customers_shopping_orders_path, class: 'btn btn-block btn-success btn-default'