config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'

  devise_for :admin_users, ActiveAdmin::Devise.config
  devise_for :customers, controllers: {
                           sessions: 'customers/sessions',
                           registrations: 'customers/registrations',
                           passwords: 'customers/passwords'
                       }

  ActiveAdmin.routes(self)
  get '/admin/products/:id/clone' => 'admin/products#new', :as => :admin_clone_product
  get '/admin/templates/:id/export' => 'admin/templates#export', :as => :admin_export_template
  get '/admin/templates/import' => 'admin/templates#import', :as => :admin_import_template
  get '/admin/shopping_orders/:id/invoice' => 'admin/shopping_orders#invoice', :as => :admin_invoice_shopping_order

  resource :categories, only: [] do
    get '/' => 'categories#index'
    get '/:slug' => 'categories#show', as: :show_slug
    get '/:id/show' => 'categories#show', as: :show_id
    get '/:category_slug/products/:slug' => 'products#show', as: :show_product_slug
    match '/:slug/tag/*slug_tags' => 'categories#tags', as: :tags, via: [:get]
  end

  match '/tag/*slug_tags' => 'categories#tags', as: :tags, via: [:get]

  resource :products, only: [] do
    get '/:slug' => 'products#show', as: :show_slug
    get '/:id/show' => 'products#show', as: :show_id
    get '/:id/add_to_shopping_cart' => 'products#add_to_shopping_cart', as: :add_to_shopping_cart
    get '/:id/delete_from_shopping_cart' => 'products#delete_from_shopping_cart', as: :delete_from_shopping_cart
  end

  resource :searches, only: [] do
    post '/' => 'searches#index'
  end

  resource :customers, only: [] do
    get '/show' => 'customers#show'
    get '/orders' => 'customers#orders'
    get '/orders/:id/invoice' => 'customers#invoice', as: :orders_invoice

    resources :addresses
    resource :shopping_carts, only: [] do
      get '/' => 'shopping_carts#show'
      post '/:product_id/update' => 'shopping_carts#update', as: :update
    end

    resource :shopping_orders, only: [] do
      get '/shipping_method' => 'shopping_orders#shipping_method'
      get '/:type/addresses' => 'shopping_orders#addresses', as: :addresses
      get '/:type/:id/save_address' => 'shopping_orders#save_address', as: :save_address

      post '/save_carrier' => 'shopping_orders#save_carrier'
      get '/checkout' => 'shopping_orders#checkout'
      get '/finalize' => 'shopping_orders#finalize'
    end
  end

  get '/locale/:locale' => 'application#change_locale', :as => 'change_locale'

  scope '/api' do
    scope '/v1' do
      scope '/data_forms' do
        post '/' => 'api/data_forms#create'
      end
    end
  end

  root 'home#index'

end

app/models/shopping_order.rb
# == Schema Information
#
# Table name: shopping_orders
#
#  billing_address           :hstore           default({}), not null
#  billing_commerce          :hstore           default({}), not null
#  carrier_id                :integer
#  carrier_retail_price      :decimal(10, 2)   default(0.0), not null
#  commerce_id               :integer
#  created_at                :datetime         not null
#  customer_id               :integer
#  id                        :integer          not null, primary key
#  order_num                 :integer          not null
#  shipping_address          :hstore           default({}), not null
#  shopping_orders_status_id :integer
#  updated_at                :datetime         not null
#
# Indexes
#
#  index_shopping_orders_on_customer_id  (customer_id)
#
# Foreign Keys
#
#  fk_rails_6cc7143c73  (customer_id => customers.id)
#  fk_rails_be0697c8ed  (commerce_id => commerces.id)
#  fk_rails_c71875ef4e  (carrier_id => carriers.id)
#

class ShoppingOrder < ActiveRecord::Base
  include ArrayLiquid

  belongs_to :carrier
  belongs_to :customer
  belongs_to :commerce
  belongs_to :shopping_orders_status
  has_many :shopping_orders_products

  def shopping_orders_products_plus_carrier
    sop = shopping_orders_products.to_a

    sop << {product: '<strong>Shipping</strong>'.html_safe}
    sop << {product: carrier, retail_price_pre_tax: 0, retail_price: 0}
    sop
  end

  def self.from_shopping_cart(sc, commerce)
    so = ShoppingOrder.new
    so.customer = sc.customer
    so.carrier = sc.carrier
    so.carrier_retail_price = sc.carrier_retail_price

    so.shipping_address = sc.shipping_address.fields
    so.billing_address = sc.billing_address.fields

    unless commerce.nil?
      so.commerce = commerce
      so.billing_commerce = commerce.billing_address
    end

    sc.shopping_carts_products.each do |scp|
      so.shopping_orders_products << scp.to_shopping_order
    end

    so
  end

  def retrieve_order_num
    if commerce.nil? || commerce.order_prefix.blank?
      str = order_num.to_s
    else
      str = created_at.strftime(commerce.order_prefix.gsub('%order_num', order_num.to_s))
    end

    str
  end

  def total_taxes
    shopping_orders_products.inject(0) do |a, e|
      a + (e.retail_price - e.retail_price_pre_tax) * e.quantity
    end
  end

  def total_products
    shopping_orders_products.inject(0) { |a, e| a + e.quantity }
  end

  def total_retail_price_pre_tax
    products_prices = shopping_orders_products.map { |e| e.retail_price_pre_tax * e.quantity }
    products_prices.reduce(:+)
  end

  def total_retail_price
    products_prices = shopping_orders_products.map { |e| e.retail_price * e.quantity }
    products_prices.reduce(:+)
  end

  def total_weight
    shopping_orders_products.inject(0) { |a, e| a + (e.product.weight * e.quantity) }
  end

  def to_liquid
    {
        'order_num' => retrieve_order_num,
        'shopping_orders_products' => array_to_liquid(shopping_orders_products),
        'total_products' => total_products,
        'total_taxes' => total_taxes,
        'total_weight' => total_weight,
        'total_retail_price_pre_tax' => total_retail_price_pre_tax,
        'total_retail_price' => total_retail_price
    }
  end
end

app/controllers/shopping_orders_controller.rb
class ShoppingOrdersController < Frontend::CommonController
  layout 'shopping'

  before_action :authenticate_customer!
  before_action :check_addresses, only: [:finalize, :shipping_method]

  def get_template_variables(template)
    super

    @variables['finalize_shopping_order_href'] = finalize_customers_shopping_orders_path
  end

  def checkout
    @carrier_id = params_shopping_order[:carrier_id]
    # TODO check for empty cart.
    add_breadcrumb(Breadcrumb.new(url: shipping_method_customers_shopping_orders_path, name: 'Checkout'))
  end

  def addresses
    @variables ||= {}

    @type = params[:type]
    @variables['customer_addresses'] = current_customer.customer_addresses

    add_breadcrumb(Breadcrumb.new(url: shipping_method_customers_shopping_orders_path, name: 'Checkout'))
    add_breadcrumb(Breadcrumb.new(url: addresses_customers_shopping_orders_path(@type), name: 'Select address'))
  end

  # TODO change this event for post.
  # TODO check param type
  def save_address
    type = params[:type]
    id = params[:id].to_i

    addresses = current_customer.customer_addresses.pluck(:id)
    if addresses.include? id
      attributes = {}
      attributes[type] = id
      sc = current_customer.shopping_cart
      unless sc.nil?
        sc.attributes = attributes
        sc.save
      end
    end

    redirect_to :shipping_method_customers_shopping_orders
  end

  def save_carrier
    sc = current_customer.shopping_cart
    unless sc.nil?
      sc.attributes = params_shopping_order
      sc.save
    end

    redirect_to :checkout_customers_shopping_orders
  end

  def shipping_method
    @carriers = Carrier.where(enabled: true)
  end

  def finalize
    sc = current_customer.shopping_cart

    unless sc.nil?
      so = ShoppingOrder.from_shopping_cart(sc, @commerce)
      unless so.save
        redirect_to :shipping_method_customers_shopping_orders, alert: 'A carrier needs to be selected.'
        return
      end

      sc.destroy
    end

    redirect_to :show_customers, notice: 'Thanks for your purchase.'
  end

  protected

  def params_shopping_order
    params.permit(:carrier_id)
  end

  def set_breadcrumbs
    add_breadcrumb(Breadcrumb.new(url: show_customers_path, name: 'Customers'))
  end

  def check_addresses
    sc = current_customer.shopping_cart

    if sc.nil?
      redirect_to :customers_shopping_carts, alert: 'Shopping cart not set.'
      return
    end

    if sc.shipping_address.nil? || sc.billing_address.nil?
      redirect_to :customers_shopping_orders,
                  alert: 'To finalize the purchase sets before the shipping and billing address.'
    end
  end
end

app/helpers/admin/shopping_orders_helper.rb
module Admin
  module ShoppingOrdersHelper
    def admin_retrieve_array_address(caddress = {})
      address_array = []

      address_array << "#{caddress['name']} #{caddress['customer_name']} #{caddress['customer_last_name']}"
      address_array << "#{caddress['cif']} #{caddress['dni']}"
      address_array << caddress['business']
      address_array << caddress['address_1']
      address_array << caddress['address_2'] unless caddress['address_2'].blank?
      address_array << "#{caddress['postal_code']} #{caddress['city']}"
      address_array << caddress['country']
      address_array << caddress['phone']
      address_array << caddress['mobile_phone']
      address_array << caddress['other']

      address_array
    end
  end
end

app/helpers/shopping_orders_helper.rb
module ShoppingOrdersHelper
  def shopping_order_status(so)
    color = ''
    status = 'Pending'

    unless so.shopping_orders_status.nil?
      color = so.shopping_orders_status.color
      status = so.shopping_orders_status.name
    end

    content_tag :div do
      concat(content_tag(:label, 'STATUS'))
      concat('<br />'.html_safe)
      concat(content_tag(:span, status, class: 'status_tag', style: "background-color: #{color};"))
    end
  end
end

app/views/shopping_orders/_invoice.html.haml
:javascript
  $(document).ready(function() {
    window.print();
  });

- commerce = shopping_order.commerce
%div.container
  %div.row
    %div.col-xs-12

      %div.row
        %div.col-xs-8
          %h2
            = image_tag @variables['commerce']['image_src'], :alt => 'Invoice'

        %div{class: 'col-xs-4 text-right'}
          %ul.list-unstyled
            %li
              %h2
                = "ORDER N.º #{shopping_order.retrieve_order_num}"
            - if !commerce.nil? && commerce.billing_address.nil?
              %li
                = render partial: 'shopping_orders/invoice_address', locals: { address: commerce.billing_address }

      %hr
      %div.row
        %div.col-xs-6
          %address
            %strong Billed To:
            - unless shopping_order.billing_address.nil?
              = render partial: 'shopping_orders/invoice_address', locals: { address: shopping_order.billing_address }

        %div{class: 'col-xs-6 text-right'}
          %address
            %strong Shipped To:
            - unless shopping_order.shipping_address.nil?
              = render partial: 'shopping_orders/invoice_address', locals: { address: shopping_order.shipping_address }

      %div.row
        %div.col-xs-6
          %address
            %strong Payment Method:
            %br
            Visa ending **** 4242
            %br
            jsmith@email.com
        %div{class: 'col-xs-6 text-right'}
          %address
            %strong
              Order Date:
            %br
            = l shopping_order.created_at, format: :long

  %div.row
    %div.col-xs12
      %div{class: 'panel panel-default'}
        %div.panel-heading
          %h3.panel-title
            %strong Order summary

        %div.panel-body
          %div.table-responsive
            %table{class: 'table table-condensed'}
              %thead
                %tr
                  %td.col-xs-1
                    %strong Quantity
                  %td.col-xs-6
                    %strong Item
                  %td{class: 'col-xs-1 text-center'}
                    %strong Price without tax
                  %td{class: 'col-xs-1 text-center'}
                    %strong Tax
                  %td{class: 'col-xs-1 text-center'}
                    %strong Price with tax
                  %td{class: 'col-xs-2 text-right'}
                    %strong Totals
              %tbody
                - shopping_order.shopping_orders_products_plus_carrier.each do |sop|
                  - if sop.is_a?(Hash)
                    %tr
                      %td.text-center
                      %td
                        = sop[:product]
                      %td.text-center
                        = sop[:retail_price_pre_tax]
                      %td.text-center
                      %td.text-center
                      %td.text-right
                        = sop[:retail_price]
                  - else
                    %tr
                      %td.text-center
                        = sop.quantity unless sop.quantity.nil?
                      %td
                        = sop.product.name
                      %td.text-center
                        = sop.retail_price_pre_tax
                      %td.text-center
                        = "#{sop.tax_rate}%"
                      %td.text-center
                        = sop.retail_price
                      %td.text-right
                        = sop.quantity * sop.retail_price if !sop.quantity.nil? && !sop.retail_price.nil?

                %tr
                  %td{class: 'no-line', 'colspan' => 5}
                    %strong Shipping
                  %td{class: 'no-line text-right'}
                    $15

                %tr
                  %td{class: 'thick-line', 'colspan' => 6}
                    %div{class: 'col-xs-offset-6 col-xs-2 text-center'}
                      %strong Subtotal without tax
                      %br
                      = "#{shopping_order.total_retail_price_pre_tax} €"
                    %div{class: 'col-xs-2 text-center'}
                      %strong Taxes
                      %br
                      = "#{shopping_order.total_taxes} €"
                    %div{class: 'col-xs-2 text-center'}
                      %strong Total
                      %br
                      = "#{shopping_order.total_retail_price} €"

app/views/shopping_orders/_invoice_address.html.haml
%ul.list-unstyled
  %li
    = "#{address['customer_name']} #{address['customer_last_name']}"
  %li
    = address['dni']
  %li
    = address['cif']
  %li
    = address['business']
  %li
    = address['address_1']
    = "<br /> #{address['address_2']}".html_safe unless address['address_2'].blank?
  %li
    = "#{address['postal_code']} #{address['city']}"
  %li
    = address['country']
  %li
    = address['phone']
  %li
    = address['mobile_phone']
  %li
    = address['other']

app/views/shopping_orders/addresses.html.haml
%h1 Select an address
%hr

%div.row
  - @variables['customer_addresses'].each do |address|
    %div.col-md-4
      %a{href: save_address_customers_shopping_orders_path(@type, address), :style => 'text-decoration: none; color: #000;'}
        = render partial: 'addresses/address', locals: {address: address}

app/views/shopping_orders/checkout.html.haml
%h1 Checkout

- sc = @variables['shopping_cart']
%ul.list-unstyled
  %li
    %div.row
      %div{class: 'col-md-6 col-xs-6'}
      %div{class: 'col-md-3 col-xs-3'}
        Price
      %div{class: 'col-md-3 col-xs-3'}
        Quantity

  - sc.shopping_carts_products.each do |scp|
    - product = scp.product
    %li.sc-list-item-border

      %div.row
        %div{class: 'col-md-6 col-xs-6'}
          %div.row
            %div{:class => 'item-image col-md-3'}
              = image_tag product.retrieve_main_image(:thumbnail)
            %div{:class => 'col-md-9 col-xs-12'}
              = product.name
        %div{class: 'col-md-3 col-xs-3'}
          %div.a-color-price
            = "#{product.retail_price} €"
        %div{class: 'col-md-3 col-xs-3'}
          = scp.quantity
  - unless sc.carrier.nil?
    %li.sc-list-item-border
      %div.row
        %div{:class => 'col-md-12 col-xs-12'}
          %strong Shipping

      %div.row
        %div{class: 'col-md-6 col-xs-6'}
          %div{:class => 'item-image col-md-3'}
            %div{class: 'delivery_option_logo'}

          %div{:class => 'col-md-9 col-xs-12'}
            %strong
              = sc.carrier.name
            %br
            = sc.carrier.delay
        %div{class: 'col-md-3 col-xs-3'}
          %div.a-color-price
            - if sc.carrier.free_carrier
              = 'Free!'
            - else
              = "#{sc.carrier_retail_price} €"
        %div{class: 'col-md-3 col-xs-3'}

  %li.sc-list-item-border
    %div.row
      %div{class: 'col-md-6'}
      %div{class: 'col-md-6 col-xs-12'}
        %div.pull-right
          %span
            = "Subtotal (#{sc.total_products} products): "
          %span.a-color-price
            = "#{sc.total_retail_price} €"

%div{class: 'row voffset2'}
  %div{class: 'col-md-6'}
    %h4 Shipping address
    %hr
      = render partial: 'addresses/address', locals: {address: sc.shipping_address}

  %div{class: 'col-md-6'}
    %h4 Billing address
    %hr
      = render partial: 'addresses/address', locals: {address: sc.billing_address}

%div{class: 'row voffset4'}
  %div{class: 'col-md-2'}
    = link_to 'Continue shopping', @variables['commerce']['root_href'], class: 'btn btn-default btn-block'
  %div{class: 'col-md-offset-8 col-md-2'}
    = link_to 'Checkout', finalize_customers_shopping_orders_path, class: 'btn btn-success btn-block'

app/views/shopping_orders/shipping_method.html.haml
%h1 Shipping options
%hr

- sc = @variables['shopping_cart']
%div{class: 'row voffset3'}
  %div{class: 'col-md-6'}
    %h4 Shipping address
    %hr
    - if sc.shipping_address.nil?
      = link_to 'Select shipping address', addresses_customers_shopping_orders_path('shipping_address_id')
    - else
      = link_to 'Select other shipping address', addresses_customers_shopping_orders_path('shipping_address_id')
      = render partial: 'addresses/address', locals: {address: sc.shipping_address}

  %div{class: 'col-md-6'}
    %h4 Billing address
    %hr
    - if sc.billing_address.nil?
      = link_to 'Select billing address', addresses_customers_shopping_orders_path('billing_address_id')
    - else
      = link_to 'Select other billing address', addresses_customers_shopping_orders_path('billing_address_id')
      = render partial: 'addresses/address', locals: {address: sc.billing_address}

%span
  Select an shipping option:

= form_tag save_carrier_customers_shopping_orders_path, method: :post do
  %div{class: 'voffset3'}
    - @carriers.each_with_index do |carrier, i|
      %div.row
        %div.col-xs-12
          %table{class: 'resume table table-bordered'}
            %tbody
              %tr
                - country_code = sc.shipping_address.country
                - cost, is_valid = carrier.calculate_shipping_cost_to(country_code, sc.total_weight)
                %td{class: 'delivery_option_radio'}
                  - if is_valid
                    = radio_button_tag :carrier_id, carrier.id, i==0
                %td{class: 'delivery_option_logo'}

                %td
                  %strong
                    = carrier.name
                  %br
                    = carrier.delay

                %td{class: 'delivery_option_price'}
                  - if is_valid
                    - if carrier.free_carrier
                      = 'Free!'
                    - else
                      = "#{cost} €"
                  - else
                    = 'Not available'

  %div{class: 'row voffset3'}
    %div{class: 'col-md-2'}
      = link_to 'Continue shopping', @variables['commerce']['root_href'], class: 'btn btn-default btn-block'
    %div{class: 'col-md-offset-8 col-md-2'}
      = submit_tag 'Checkout', class: 'btn btn-success btn-block'